export const iconList = [
    null,
    null,
    null,
    null,
    {
        src:
            "https://img.icons8.com/offices/100/php-logo.png",
    },
    {
        src:
            "https://img.icons8.com/fluency/96/000000/python.png",
    },
    {
        src:
            "https://img.icons8.com/color/48/000000/ruby-programming-language.png"
    },
    {
        src:
            "https://img.icons8.com/color/96/000000/html-5--v1.png"
    },
    null,
    {
        src:
            "https://img.icons8.com/color/100/000000/c-sharp-logo.png"
    },
    null,
    {
        src:
        "https://img.icons8.com/color/48/000000/mysql-logo.png"
    },
    null,
    null,
    null,
    null,
    {
        src:
            "https://img.icons8.com/nolan/100/raspberry-pi.png"
    },
    null,
    {
        src:
                "https://img.icons8.com/color/96/000000/javascript--v2.png"
    },
    null,
    {
        src: "https://img.icons8.com/color/96/000000/github--v1.png"
    },
    null,
    null,
    null,
    null,
    null,
    {
        src:
        "https://img.icons8.com/color/96/000000/typescript.png"
    },
    null,
    null,
    null,
    null,
    null,
    {
        src:
            "https://img.icons8.com/color/96/000000/angularjs.png"
    },
    null,
    {
        src:
        "https://img.icons8.com/nolan/100/heroku.png"
    },

    {
        src:
            "https://img.icons8.com/color/96/000000/java-coffee-cup-logo--v1.png"
    },
    null,
    null,
    null,
    null,
    {
        src:
            "https://img.icons8.com/color/96/000000/npm.png"
    },
    {
        src:
            "https://img.icons8.com/nolan/96/react-native.png"
    },
    null,
    {
        src:
            "https://img.icons8.com/color/96/000000/nodejs.png"
    },
    null,
    null,
    {
        src:
            "https://img.icons8.com/ios/50/000000/sass.png"
    },
    null,

    null,
    null,
    null,
    {
        src:
            "https://img.icons8.com/color/96/000000/graphql.png"
    },
    null,
    null,
    {
        src:
            "https://img.icons8.com/color/96/000000/swift.png"
    },
    null
];